image: Visual Studio 2019

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $directory_path = "$env:APPVEYOR_BUILD_FOLDER\"
      $solutions = Get-ChildItem -Path $directory_path -Recurse -Include *.sln

build_script:
  - ps: |
      foreach ($solution in $solutions) 
      {
        dotnet build $solution
        if ($LastExitCode -ne 0) 
        { 
          $host.SetShouldExit($LastExitCode)  
        }
      }

test_script:
  - ps: |
      foreach ($solution in $solutions) 
      {
        dotnet test $solution
        if ($LastExitCode -ne 0) 
        { 
          $host.SetShouldExit($LastExitCode)  
        }
      }